[tool.poetry]
name = "cman-spider"
version = "0.0.1"
description = "Spider for CMAN"
authors = ["XYCode <xycode-xyc@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
